include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_types_as_parameter_names: true
    avoid_void_async: true
    empty_statements: true
    eol_at_end_of_file: true
    no_duplicate_case_values: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_single_quotes: true
    recursive_getters: true
    unnecessary_await_in_return: true
    unnecessary_late: true
